### ISSUE TITLE
Still having speech message every 4 hours

### ISSUE THREAD

**Issue by pauluzs** [Anthony96922/st-keygen#1]
Hi and thanks for the st-keygen.

The keygen seems to work fine, however every 4 hours there is still a speech message played "This sound is processed by stereo..." 

Already tried running crude a shell license server replying "ok" to the startup check, preventing the "invalid licence" when running with an active internet connection. Only this doesn't seem to solve the problem.

licence server check shell script: (replace (dot) with real dots)

grep -q "vvv(dot)stereotool(dot)com" /etc/hosts || sudo sh -c "echo 127.0.0.1       vvv(dot)stereotool(dot)com >> /etc/hosts"
mkdir -p cgi-bin
touch cgi-bin/chk.pl
grep -q "ok" cgi-bin/chk.pl || echo ok > cgi-bin/chk.pl
sudo python3 -m http.server --bind vvv(dot)stereotool(dot)com 80 & SERVER_PID=$! 
./stereo_tool_gui_64 
sudo kill $SERVER_PID
rm -rf cgi-bin

**Comment by Anthony96922** [comment]
What features are you using?

**Comment by pauluzs** [comment]
Testing with stereo_tool_gui_jack_64 9.92 to generate a fm mpx signal.

Enabled:
Declipper
Auto/BASS EQ/Dyn spd/AGC34/Progressive/Speech
Advanced Clipper, FM Composite clipper
Natural Dynamics
FM (Pre-emphasis,stereo,RDS

![image](https://user-images.githubusercontent.com/11356942/210120342-46eec58c-ee59-4465-a878-be988dd4dd65.png)

**Comment by Anthony96922** [comment]
Try adding -f 0x49f508df to the keygen. Might have to do with AGC 3/4 but I'm not sure.

**Comment by pauluzs** [comment]
> Try adding -f 0x49f508df to the keygen. Might have to do with AGC 3/4 but I'm not sure.

 Unfortunally that doesn't seem to fix it

**Comment by Anthony96922** [comment]
Try 0x49f50fff

**Comment by pauluzs** [comment]
> Try 0x49f50fff

Also not correct

**Comment by Anthony96922** [comment]
Try 0x49f52fff

**Comment by pauluzs** [comment]
> Try 0x49f52fff

Missed again, any idea what option is causing this?

**Comment by Anthony96922** [comment]
I think it might be the declipper. Try 0xeff52fff

**Comment by pauluzs** [comment]
> I think it might be the declipper. Try 0xeff52fff

disables FM proccessing

> Edit: or 0x6ff52ff3 (this might work better)

Also not correct

**Comment by Anthony96922** [comment]
Try 0x49e508db

**Comment by pauluzs** [comment]
> 0x49e508db

nope

**Comment by pauluzs** [comment]
I noticed the keygen sometimes not giving the correct name after using some suggested masks, and it needs to be run a second time to display the name again in the license info.
This happened after directly after using mask 0x49f508df and again using it without a mask after using 0x49e508db as far i can recall in bash.
send me a gmail if u want a log of this

**Comment by Anthony96922** [comment]
Send me an email. Thanks.

**Comment by pauluzs** [comment]
started out with all new settings from scratch, which seem to solve the problem, still haven't found what actually caused this.
