### ISSUE TITLE
ST announcement still playing

### ISSUE THREAD

**Issue by SpiderBlocker** [Anthony96922/st-keygen#2]
Hi there!
Your earlier fix removing the "_Composite Clipper is used without license_" indeed removes that message, however after exactly 4 hours of running ST9.92 still an audio advertisement clip is played ("_This sound is processed by StereoTool ..._ blabla") mixed through the FM-output), even after a fresh install on a computer without Internet connection.
All available licenses are marked green in ST and the only remaining nagging is that this audio advertisement is played after 4 hours run-time on FM-output. I am only using all FM-professional features, including Composite Clipper. I have µMPX, BIMP and other features disabled.

**Comment by Anthony96922** [comment]
You might be facing the same issue as #1. Disable the composite clipper then restart ST. If the announcement does not play after 4 hours then it means not all bits for the composite clipper are not being set. I will test various feature masks again to see what stops the announcements.

**Comment by SpiderBlocker** [comment]
Hi again. I tested with composite clipper disabled and ST restarted, but the announcement keeps popping up after 4 hours. Maybe one of the other features is to blame, unless it would be caused by the fact that composite clipper is not properly registered, regardless whether it is active or not? Since the announcement litterally plays "_This sound is processed by Stereotool_", one may expect it to be related to one of the sound processing features and not something like FM, Advanced RDS or µMPX.
![Licenes](https://github.com/Anthony96922/st-keygen/assets/139555167/b16fb338-af12-456c-a1f2-1617989a5836)
Do you have any ideas for speeding up testing this, as it will take 4 hours for scanning along each of remaining features this way? I already found that the 4-hours timer is not related to the windows clock time, so it can't be tricked that way :-(
Thx!

**Comment by SpiderBlocker** [comment]
Update: I have tested with all features disabled and still the announcement pops up. Now testing again with composite clipper deactivated and unregistered (removed it from the feature mask).

**Comment by Anthony96922** [comment]
Try using 0x49e508db. I think bit 3 (0x00000004) might be for the event FM license and that is what might be causing the message.

**Comment by SpiderBlocker** [comment]
With 0x49e508db ST displays a red message "FM processing used without license".

**Comment by reztek** [comment]
Just to add to the conversation, I'm using 0xbe27b897 with the command line version of ST and get the message every 12hours.
Only Advanced Clipper, Natural Dynamics, Advanced Dynamics and Dehummer enabled.

**Comment by Anthony96922** [comment]
I don't get the message with my "Test all license options" preset for some reason. If you can, send me your preset through email and I can try diagnosing further.

**Comment by Anthony96922** [comment]
> Just to add to the conversation, I'm using 0xbe27b897 with the command line version of ST and get the message every 12hours. Only Advanced Clipper, Natural Dynamics, Advanced Dynamics and Dehummer enabled.

That is a strange mask. The program defaults to 0x49e508df. Where did you get that from? (Might be the checksum.)

**Comment by reztek** [comment]
> That is a strange mask. The program defaults to 0x49e508df. Where did you get that from? (Might be the checksum.)

ORd the bits manually by the keygen source reference, for testing and passed to the keymaker using "-f". Same thing (audio message everey 12h) happens with the default 0x49e508df.

**Comment by Anthony96922** [comment]
> > That is a strange mask. The program defaults to 0x49e508df. Where did you get that from? (Might be the checksum.)
> 
> ORd the bits manually by the keygen source reference, for testing, and passed to the keymaker using "-f". Same thing (audio message everey 12h) happens with the default 0x49e508df.
> 
> PS.: BTW, AFAICT the command line of ST doesn't do any online checking, so whatever license check that's failing is happening locally.

Try 0x00604002

**Comment by Anthony96922** [comment]
> With 0x49e508db ST displays a red message "FM processing used without license".

Try 0xeff52fff. This enables all unknown bits.

**Comment by SpiderBlocker** [comment]
Looks promising for the first 4 hours and 5 minutes so far! I shall further test tomorrow when I will be back home again.
-------- Oorspronkelijk bericht --------Van: Anthony96922 ***@***.***> Datum: 20-07-2023  05:47  (GMT+08:00) Aan: Anthony96922/st-keygen ***@***.***> Cc: SpiderBlocker ***@***.***>, Author ***@***.***> Onderwerp: Re: [Anthony96922/st-keygen] ST announcement still playing (Issue #2) 

With 0x49e508db ST displays a red message "FM processing used without license".

Try 0xeff52fff. This enables all unknown bits.

**Comment by pressurefm** [comment]
Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project

**Comment by reztek** [comment]
Tested with "0xeff52fff" and got no messages after 24 hours running ST. Solved for me.

**Comment by Anthony96922** [comment]
> Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project

Works for 10.02 beta 087

**Comment by pressurefm** [comment]
> > Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project
> 
> Works for 10.02 beta 087

this is very good, could you help me install your key?  I have raspberry 4, and HiFiBerry dac + adc.i am new to linux.... tnx

**Comment by Anthony96922** [comment]
> > > Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project
> > 
> > 
> > Works for 10.02 beta 087
> 
> this is very good, could you help me install your key? I have raspberry 4, and HiFiBerry dac + adc.i am new to linux.... tnx

Run make-regkey with the name you want to get a registration key.

Example: ./make-regkey 'some name'

Then pass the key with the -k flag.

**Comment by SpiderBlocker** [comment]
> > > > Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project
> > > 
> > > 
> > > Works for 10.02 beta 087
> > 
> > 
> > this is very good, could you help me install your key? I have raspberry 4, and HiFiBerry dac + adc.i am new to linux.... tnx
> 
> Run make-regkey with the name you want to get a registration key.
> 
> Example: ./make-regkey 'some name'
> 
> Then pass the key with the -k flag.

**Comment by SpiderBlocker** [comment]
Hi!
I have made FM-preset from scratch again in fresh ST 9.92 installment, reg'd with 0xeff52fff flag and ST blocked through firewall. All licenses show green, but still 4h announcement is played through FM-output. I have e-mailed that preset to you (thecube); if you could have a look, would be great!

**Comment by pressurefm** [comment]
> > > > > Please tell me what version of the stereo tool does this work for ?! I'm new, I'm very interested in this project
> > > > 
> > > > 
> > > > Works for 10.02 beta 087
> > > 
> > > 
> > > this is very good, could you help me install your key? I have raspberry 4, and HiFiBerry dac + adc.i am new to linux.... tnx
> > 
> > 
> > Run make-regkey with the name you want to get a registration key.
> > Example: ./make-regkey 'some name'
> > Then pass the key with the -k flag.

**I installed this archive on a flash card, and updated it to the latest version via the web interface. How can I run this code?
I'm new. Sorry for such a stupid question.

https://forums.stereotool.com/viewtopic.php?f=14&t=32883&start=30**

**Comment by dole738** [comment]
Hello,
How does it works please ?
Chocolatey is installed in my Windows 10. Which line of code should I run in Windows powershell ? Is there a tutorial ?
Thank you

**Comment by LoenieAB** [comment]
Hi again!

Finally found which feature causes the 4h announcement. I Have been scanning along more than 30 four-hour runs since July 25th and of course it was the very last possibility left :-)

It is definitely the Advanced Clipper. It's not the Advanced Cipper as a whole, but a subsetting of it. I can further narrow down the exact subsetting if needed; pls advise if I need to.

**Comment by SpiderBlocker** [comment]
All good now!
