### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by brane0690** [Anthony96922/st-keygen#3]
Can this work on enterprise versions?
Will it work for beta 089 Enterprise Windows and Linux?
I mean without announcement: "This is processed..."

**Comment by Anthony96922** [comment]
Yes

**Comment by brane0690** [comment]
Thank you. I will test it in the next few days and let you know my feedback :)

**Comment by brane0690** [comment]
I just tried to enter generated key and got this after few minutes: Invalid key in use. At first key was accepted.

**Comment by Anthony96922** [comment]
Buy a basic license then use the name from that.
